'use strict';
const $=id=>document.getElementById(id),gains=[0,9,14,27,37,77,87,125,144,157,166,197,207,229,254,280,297,328,338,364,372,386,402,421,434,439,445,480,496];
const bands=[['40m',7100000,'LSB'],['20m',14200000,'USB'],['6m',50150000,'USB'],['AIRBAND',118000000,'AM'],['MARINE UK',156800000,'NFM'],['PMR UK',446006250,'NFM'],['2m',145500000,'NFM'],['1.25m',222100000,'NFM'],['70cm',433500000,'NFM'],['33cm',902100000,'NFM'],['23cm',1296100000,'NFM'],['13cm',2300000000,'NFM'],['90m',3300000,'AM'],['50m',6000000,'AM']];
const widths={LSB:[1800,2400,3000],USB:[1800,2400,3000],CW:[250,500,1000],AM:[5000,9000,12000],NFM:[8000,12500,16000,25000],WFM:[150000,180000,200000]};
let driverInfo='Checking V4 driver identity',audioRate=0,captureDrops=0,usbQueue=0;
let freq=4006934,bfreq=14200000,bmode='USB',mode='LSB',bandwidth=2400,span=100000,waterSpanChoice=0,dxOverlay=false,dxHits=[],dxSpots=[],dxTimer=null,dxBusy=false,dxError='',rf=85,af=80,agc=true,live=false,ws,context,player,frozen=false,waterOn=true,waterGain=0,waterFloor=-100,anf=false,notch=false,nb=false,nr=false,nbStrength=50,nrStrength=40,notchHz=1000,notchWidth=80,pre=false,att=false,specRef=-30,specRange=100,specAvg=0,smoothBins=null,smoothSeq=-1,scanTimer=null,scanIndex=0,bins=null,level=-120,seq=0,lastFrame=0,sourcesReceived=0,memory=[],toastTimer;
try{memory=JSON.parse(localStorage.getItem('hamtec-direct-memory')||'[]').filter(m=>Number.isFinite(m.freq)&&m.freq>=500000&&m.freq<=1766000000&&widths[m.mode]);}catch{}
function format(value){const s=String(Math.round(value));return s.replace(/\B(?=(\d{3})+(?!\d))/g,'.');}
function message(text){$('message').textContent=text;$('message').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('message').style.display='none',4500);}
function send(){if(live&&ws.readyState===1)ws.send(JSON.stringify({freq,mode,bandwidth,gain:effectiveGain(),agc,anf,notch,nb,nr,nb_strength:nbStrength,nr_strength:nrStrength,notch_hz:notchHz,notch_width:notchWidth,squelch:+$('sql').value,ppm:+$('ppm').value}));}
function tune(value){if(!Number.isFinite(value)||value<500000||value>1766000000){message('RTL-SDR tuning range: 0.5–1766 MHz');$('freq').value=format(freq);return}freq=Math.round(value);$('freq').value=format(freq);fitFrequency();$('center').textContent=format(freq);$('freq-entry').value=(freq/1e6).toFixed(6);bins=null;smoothBins=null;smoothSeq=-1;clearWater();send();}
function parseFrequency(text){text=text.trim();if(!text)return NaN;return /^\d+(?:\.\d{3}){2,3}$/.test(text)?Number(text.replaceAll('.','')):Number(text)*1e6;}
function setMode(m){mode=m;$('mode').value=m;const options=widths[m];bandwidth=options.includes(bandwidth)?bandwidth:(m==='NFM'?25000:options[1]);$('filter').replaceChildren();for(const v of options){const o=document.createElement('option');o.value=v;o.textContent=v>=1000?v/1000+' kHz':v+' Hz';$('filter').append(o)}$('filter').value=bandwidth;$('mode-text').textContent=m==='NFM'?'FM':m;$('filter-text').textContent=bandwidth/1000+'k';updateNoise();document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===m));send();}
function step(n){tune(freq+n*+$('step').value)}
function stopScan(){clearInterval(scanTimer);scanTimer=null;$('scan').classList.remove('scanning');}
bands.forEach(([name,hz,m],i)=>{const b=document.createElement('button');b.textContent=name;b.title=hz/1e6+' MHz';if(name==='AIRBAND'){b.title='Airband 118–137 MHz · AM · starts at 118 MHz';const range=document.createElement('span');range.className='band-range';range.textContent='118–137 MHz';b.append(range)}b.disabled=hz>1766000000;if(b.disabled)b.title='Outside RTL-SDR frequency coverage';if(name==='MARINE UK'||name==='PMR UK')b.title=name==='MARINE UK'?'UK marine voice presets · starts on channel 16':'UK analogue PMR446 · 16 channels';b.onclick=()=>{if(name==='MARINE UK'||name==='PMR UK'){openChannels(name);return}stopScan();setMode(m);tune(hz)};$('band-list').append(b)});
function nextBand(direction){const available=bands.filter(b=>b[1]<=1766000000);let nearest=available.reduce((best,b,i)=>Math.abs(b[1]-freq)<Math.abs(available[best][1]-freq)?i:best,0);nearest=(nearest+direction+available.length)%available.length;setMode(available[nearest][2]);tune(available[nearest][1]);}
$('prev').onclick=()=>nextBand(-1);$('next').onclick=()=>nextBand(1);$('up').onclick=()=>step(1);$('down').onclick=()=>step(-1);$('freq').onchange=e=>tune(parseFrequency(e.target.value));$('freq').onkeydown=e=>{if(e.key==='Enter')e.target.blur();if(e.key==='Escape'){e.target.value=format(freq);e.target.blur()}if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();stopScan();step(e.key==='ArrowUp'?1:-1)}};$('mode').onchange=e=>setMode(e.target.value);$('filter').onchange=e=>{bandwidth=+e.target.value;$('filter-text').textContent=bandwidth/1000+'k';send()};$('span').onchange=e=>{span=+e.target.value;if(!waterSpanChoice)clearWater();if(!frozen)draw(false)};$('step').onchange=()=>{const hz=+$('step').value;$('step-label').textContent='STEP '+hz;$('freq-step').textContent='STEP '+(hz>=1000?hz/1000+' kHz':hz+' Hz')};$('step-label').onclick=()=>{const s=$('step');s.selectedIndex=(s.selectedIndex+1)%s.options.length;s.onchange()};
$('freq').title='Click to enter MHz; mouse wheel or arrow keys tune by STEP';$('freq').onclick=()=> $('freq').select();$('freq').addEventListener('wheel',e=>{e.preventDefault();if(!e.deltaY)return;stopScan();step(e.deltaY<0?1:-1)},{passive:false});
$('wf-gain').oninput=()=>{waterGain=+$('wf-gain').value;$('wf-gain-value').textContent=(waterGain>0?'+':'')+waterGain+' dB';clearWater();if(!frozen)draw();try{localStorage.setItem('hamtec-water-gain',String(waterGain))}catch{}};try{const g=Number(localStorage.getItem('hamtec-water-gain'));if(Number.isFinite(g)&&g>=-60&&g<=60)$('wf-gain').value=g}catch{}

for(const [label,m]of[['LSB','LSB'],['USB','USB'],['CW','CW'],['AM','AM'],['FM','NFM'],['WFM','WFM'],['DIG',null]]){const b=document.createElement('button');b.textContent=label;if(m){b.dataset.mode=m;b.onclick=()=>setMode(m)}else{b.disabled=true;b.title='Digital decoding not implemented'}$('modes').append(b)}
$('swap').onclick=()=>{const f=freq,m=mode;setMode(bmode);tune(bfreq);bfreq=f;bmode=m;$('freq-b').textContent=format(bfreq)};$('active-vfo').onclick=$('swap').onclick;
function effectiveGain(){const base=gains[Math.round(rf/100*28)],wanted=base+(pre?100:att?-200:0);return gains.reduce((best,g)=>Math.abs(g-wanted)<Math.abs(best-wanted)?g:best,gains[0])}
function updateFront(){$('pre').textContent=pre?'ON':'OFF';$('att').textContent=att?'ON':'OFF';$('pre').classList.toggle('green',pre);$('att').classList.toggle('green',att);$('agc').textContent=agc?'MED':'OFF';$('agc').classList.toggle('green',agc);$('rf').textContent=agc?'AUTO':(effectiveGain()/10).toFixed(1);$('rf').title='RTL tuner gain in dB; manual base '+(gains[Math.round(rf/100*28)]/10).toFixed(1)+' dB'}
function updateNoise(){$('nb').textContent=nb?'ON':'OFF';$('nr').textContent=nr?'ON':'OFF';$('nb').classList.toggle('green',nb);$('nr').classList.toggle('green',nr);const bypass=anf&&!['LSB','USB','AM','NFM'].includes(mode);$('anf').textContent=bypass?'BYP':anf?'ON':'OFF';$('anf').classList.toggle('green',anf&&!bypass);$('notch').textContent=notch?'ON':'OFF';$('notch').classList.toggle('green',notch)}
$('pre').onclick=()=>{pre=!pre;att=false;agc=false;updateFront();send();message('PRE '+(pre?'ON':'OFF')+' · tuner gain '+(effectiveGain()/10).toFixed(1)+' dB')};
$('att').onclick=()=>{att=!att;pre=false;agc=false;updateFront();send();message('ATT '+(att?'ON':'OFF')+' · tuner gain '+(effectiveGain()/10).toFixed(1)+' dB')};
$('anf').onclick=()=>{anf=!anf;updateNoise();send();message(anf?(mode==='CW'||mode==='WFM'?'ANF bypassed for '+mode:'Automatic tone notch ON'):'Automatic tone notch OFF')};
$('notch').onclick=()=>{notch=!notch;updateNoise();send();message('Audio notch '+(notch?'ON at '+$('notch-hz').value+' Hz':'OFF'))};
$('apply-notch').onclick=()=>{const hz=+$('notch-hz').value,width=+$('notch-width').value;if(!Number.isFinite(hz)||!Number.isFinite(width)||hz<100||hz>12000||width<20||width>500){$('notch-hz').value=notchHz;$('notch-width').value=notchWidth;message('Notch centre: 100–12000 Hz; width: 20–500 Hz');return}notchHz=Math.round(hz);notchWidth=Math.round(width);$('notch-hz').value=notchHz;$('notch-width').value=notchWidth;send();message('Notch settings applied; '+(notch?'filter is ON':'press NOTCH to enable'))};
$('agc').onclick=()=>{agc=!agc;if(agc){pre=false;att=false}updateFront();send()};
function gain(direction){rf=Math.max(0,Math.min(100,rf+direction*5));agc=false;updateFront();send()}
function volume(direction){af=Math.max(0,Math.min(100,af+direction*5));$('af').textContent=af;if(player)player.volume(af/100);}
$('rf-down').onclick=()=>gain(-1);$('rf-up').onclick=()=>gain(1);$('af-down').onclick=()=>volume(-1);$('af-up').onclick=()=>volume(1);$('sql').oninput=()=>{$('sql-value').textContent=$('sql').value+' dBFS';send()};$('ppm').onchange=()=>{if(!Number.isFinite(+$('ppm').value)||Math.abs(+$('ppm').value)>200){$('ppm').value=0;message('PPM correction must be between −200 and 200')}$('ppm').value=Math.round(+$('ppm').value);send()};
$('water-toggle').onclick=()=>{waterOn=!waterOn;$('water-toggle').classList.toggle('green',waterOn);$('water-toggle').querySelector('span').textContent=waterOn?'ON':'OFF'};$('scope').onclick=()=>{frozen=!frozen;$('scope').classList.toggle('selected',frozen);message(frozen?'Display held; reception audio continues':'Display resumed')};
function scan(){if(scanTimer){stopScan();return}if(!live){message('USB receiver is not connected');return}const list=memory.length?memory:bands.filter(b=>b[1]<=1766000000).map(b=>({freq:b[1],mode:b[2]}));scanIndex=0;const tick=()=>{const m=list[scanIndex++%list.length];setMode(m.mode);tune(m.freq)};tick();scanTimer=setInterval(tick,2000);$('scan').classList.add('scanning');message('Scanning '+(memory.length?'memories':'band presets')+'; press SCAN to stop')}
$('scan').onclick=$('all-scan').onclick=scan;
function details(){const age=lastFrame?Math.round((performance.now()-lastFrame)/1000):'—';$('details').textContent=`USB: ${live?'connected':'disconnected'} · fresh frame: ${seq} · age: ${age}s · Audio: ${player?.enabled?'ON':'OFF'} · browser: ${context?.state||'not started'} · PCM blocks: ${sourcesReceived} · audio RMS: ${(player?.rms||0).toFixed(4)} · PCM production: ${Math.round(audioRate)} samples/s (target 48000) · USB drops: ${captureDrops} · USB queue: ${usbQueue} · audio buffer: ${Math.round((player?.buffered||0)/48)}ms · gaps: ${player?.underruns||0} · skips: ${player?.overruns||0} · ${driverInfo}`;}
function settings(){details();$('settings').showModal()};for(const id of['usb','gear','menu','system','mem','rit'])$(id).onclick=settings;$('close').onclick=()=>$('settings').close();$('tune').onclick=()=>{$('freq').focus();$('freq').select()};$('apply-frequency').onclick=()=>tune(parseFrequency($('freq-entry').value));
function renderMemory(){const list=$('memories');list.replaceChildren();memory.forEach((m,i)=>{const row=document.createElement('div');row.className='memory-row';const b=document.createElement('button');b.textContent=format(m.freq)+' '+m.mode;b.onclick=()=>{setMode(m.mode);tune(m.freq);$('settings').close()};const x=document.createElement('button');x.textContent='×';x.setAttribute('aria-label','Delete memory');x.onclick=()=>{memory.splice(i,1);persist();renderMemory()};row.append(b,x);list.append(row)})}
function persist(){try{localStorage.setItem('hamtec-direct-memory',JSON.stringify(memory))}catch{message('Memories will last only for this session')}}$('save').onclick=()=>{if(!memory.some(m=>m.freq===freq&&m.mode===mode))memory.push({freq,mode});persist();renderMemory();message('Frequency saved')};
async function ensureAudio(){if(!context||context.state==='closed'){context=new AudioContext({sampleRate:48000});player=null;}if(!player){player=await PCMPlayer.create(context);player.volume(af/100)}await context.resume();if(context.state!=='running')throw Error('Browser audio is suspended. Click POWER again.');}
async function toggleAudio(){try{await ensureAudio();if(player.enabled){player.stop();$('power').classList.remove('selected');message('Receiver audio muted')}else{player.enabled=true;$('power').classList.add('selected');message(live?'Receiver audio enabled':'Audio enabled; waiting for USB connection')}details();}catch(e){message(e.message)}}
$('power').onclick=$('audio-enable').onclick=toggleAudio;
$('test').onclick=async()=>{try{await ensureAudio();const osc=context.createOscillator(),g=context.createGain();g.gain.value=.15;osc.frequency.value=700;osc.connect(g);g.connect(context.destination);osc.start();osc.stop(context.currentTime+.5);message('Speaker test: 700 Hz tone for half a second')}catch(e){message(e.message)}};
function connect(){ws=new WebSocket(`ws://${location.host}/ws`);ws.binaryType='arraybuffer';ws.onmessage=e=>{if(typeof e.data!=='string'){sourcesReceived++;if(player)player.push(new Float32Array(e.data));return}let j;try{j=JSON.parse(e.data)}catch{return}if(j.type==='connected'){live=true;driverInfo=j.device?.summary||'Driver identity unavailable';$('live').textContent=j.device?.v4?'V4 LIVE':'USB LIVE';send();message(j.device?.v4?'Blog V4 detected. Press POWER for audio.':'USB connected. Check SYSTEM STATUS for V4 HF detection.')}else if(j.type==='spectrum'){bins=j.bins;level=j.level;seq=j.seq;audioRate=j.audio_rate||0;captureDrops=j.capture_drops||0;usbQueue=j.usb_queue||0;lastFrame=performance.now();if(!frozen)draw()}else if(j.type==='error'){message(j.message);$('details').textContent=j.message}};ws.onclose=()=>{live=false;bins=null;stopScan();player?.stop();$('live').textContent='USB OFF';message('USB stream stopped. Check the console window and reconnect/restart.');draw()};ws.onerror=()=>message('Cannot connect to the local receiver. Run the Windows launcher.');}
const spec=$('spec'),water=$('water'),waterOverlay=$('water-overlay'),sx=spec.getContext('2d'),wx=water.getContext('2d'),ox=waterOverlay.getContext('2d');
function clearWater(){wx.fillStyle='#020c36';wx.fillRect(0,0,water.width,water.height);drawWaterOverlay()}
function waterfallSpan(){return waterSpanChoice||span}
function estimateWaterFloor(data,viewSpan=waterfallSpan()){
 const lo=Math.max(0,Math.floor((.5-viewSpan/2/1024000)*data.length)),hi=Math.min(data.length,Math.ceil((.5+viewSpan/2/1024000)*data.length));
 const levels=data.slice(lo,hi).filter(v=>Number.isFinite(v)&&v>-119.5).sort((a,b)=>a-b);
 return levels.length?levels[Math.floor(levels.length*.5)]:-120;
}
function colour(v,floor=waterFloor){
 const excess=v-floor,adjusted=excess+waterGain;
 // Gain cannot turn the estimated noise floor into yellow. A bin must
 // independently clear the noise gate before warm signal colours apply.
 if(excess<Math.max(6,8-Math.max(0,waterGain)/15)||adjusted<12){const t=Math.max(0,Math.min(1,excess/8));return [2,Math.round(12+20*t),Math.round(55+65*t)]}
 const stops=[[12,[255,245,135]],[20,[255,224,60]],[28,[255,140,20]],[38,[255,30,20]],[50,[255,0,0]]];
 for(let i=1;i<stops.length;i++){if(adjusted<=stops[i][0]){const [lo,a]=stops[i-1],[hi,b]=stops[i],t=(adjusted-lo)/(hi-lo);return a.map((c,j)=>Math.round(c+(b[j]-c)*t))}}return stops.at(-1)[1];
}
function sampleBins(data,offset,pixelHz){
 const centre=(offset/1024000+.5)*data.length,width=pixelHz/1024000*data.length;
 if(width<=1){const at=Math.max(0,Math.min(data.length-1,centre)),lo=Math.floor(at),hi=Math.min(data.length-1,lo+1);return data[lo]+(data[hi]-data[lo])*(at-lo)}
 const lo=Math.max(0,Math.ceil(centre-width/2)),hi=Math.min(data.length-1,Math.floor(centre+width/2));let peak=-120;for(let i=lo;i<=hi;i++)peak=Math.max(peak,data[i]);return peak;
}
function draw(advanceWater=true){
 const w=spec.width,h=spec.height,scale=w/1000,left=32*scale,top=5*scale,bottom=h-22*scale,floor=specRef-specRange;
 sx.fillStyle='#000000';sx.fillRect(0,0,w,h);sx.strokeStyle='#153b2a';sx.lineWidth=scale;sx.font=(10*scale)+'px Arial';sx.fillStyle='#91ba9c';
 const project=v=>Math.max(top,Math.min(bottom,top+(specRef-v)/specRange*(bottom-top)));
 for(let db=Math.floor(specRef/20)*20;db>=floor;db-=20){const y=project(db);sx.beginPath();sx.moveTo(left,y);sx.lineTo(w,y);sx.stroke();sx.fillText(db,scale,y+3*scale)}
 for(let i=0;i<=8;i++){const x=left+(w-left)*i/8;sx.beginPath();sx.moveTo(x,top);sx.lineTo(x,bottom);sx.stroke();sx.textAlign=i===0?'left':i===8?'right':'center';sx.fillText(((freq-span/2+span*i/8)/1e6).toFixed(3),x,h-5*scale)}sx.textAlign='left';
 if(bins){
  if(!smoothBins||smoothBins.length!==bins.length){smoothBins=bins.slice();smoothSeq=seq}
  else if(smoothSeq!==seq){const weight=specAvg/100;smoothBins=bins.map((v,i)=>weight*smoothBins[i]+(1-weight)*v);smoothSeq=seq}
  sx.strokeStyle='#50ff85';sx.lineWidth=1.5*scale;sx.beginPath();
  for(let x=left;x<w;x++){const offset=((x-left)/(w-left)-.5)*span,y=project(sampleBins(smoothBins,offset,span/(w-left)));if(x===left)sx.moveTo(x,y);else sx.lineTo(x,y)}sx.stroke();
  if(waterOn&&advanceWater){const viewSpan=waterfallSpan();waterFloor=estimateWaterFloor(bins,viewSpan);const rows=+$('speed').value;wx.drawImage(water,0,0,water.width,water.height,0,rows,water.width,water.height);const line=wx.createImageData(water.width,rows);for(let x=0;x<water.width;x++){const offset=((x+.5)/water.width-.5)*viewSpan,c=colour(sampleBins(bins,offset,viewSpan/water.width));for(let y=0;y<rows;y++){const i=(y*water.width+x)*4;line.data[i]=c[0];line.data[i+1]=c[1];line.data[i+2]=c[2];line.data[i+3]=255}}wx.putImageData(line,0,0)}
 }else{sx.font=(12*scale)+'px Arial';sx.fillStyle='#739982';sx.fillText(live?'Waiting for fresh I/Q…':'USB receiver disconnected',w*.35,h*.5)}
 drawSpectrumMarker(left,w,top,bottom);drawWaterOverlay();
 $('needle').setAttribute('transform',`rotate(${Math.max(-65,Math.min(65,(level+60)/50*65))} 125 122)`);
}
function spectrumSettings(){specRef=+$('spec-ref').value;specRange=+$('spec-range').value;specAvg=+$('spec-avg').value;$('spec-ref-value').textContent=specRef+' dB';$('spec-range-value').textContent=specRange+' dB';$('spec-avg-value').textContent=specAvg+'%';smoothBins=null;if(!frozen)draw(false);try{localStorage.setItem('hamtec-spectrum',JSON.stringify({ref:specRef,range:specRange,avg:specAvg}))}catch{}}
for(const id of ['spec-ref','spec-range','spec-avg'])$(id).oninput=spectrumSettings;
try{const saved=JSON.parse(localStorage.getItem('hamtec-spectrum')||'null');if(saved){for(const [id,key,min,max] of [['spec-ref','ref',-90,0],['spec-range','range',40,140],['spec-avg','avg',0,90]])if(Number.isFinite(saved[key])&&saved[key]>=min&&saved[key]<=max)$(id).value=saved[key]}}catch{}
function filterEdges(){return mode==='USB'?[150,bandwidth]:mode==='LSB'?[-bandwidth,-150]:[-bandwidth/2,bandwidth/2]}
function drawSpectrumMarker(left,w,top,bottom){const centre=(left+w)/2,[lo,hi]=filterEdges(),x1=Math.max(left,centre+lo/span*(w-left)),x2=Math.min(w,centre+hi/span*(w-left));sx.fillStyle='rgba(255,232,75,.08)';sx.fillRect(x1,top,Math.max(0,x2-x1),bottom-top);sx.strokeStyle='#ffe85b';sx.lineWidth=w/1000;sx.beginPath();sx.moveTo(centre,top);sx.lineTo(centre,bottom);sx.stroke();sx.fillStyle='#ffe85b';sx.font=(10*w/1000)+'px Arial';sx.textAlign='center';sx.fillText('RX',centre,top+12*w/1000);sx.textAlign='left'}
function visibleDX(){const half=waterfallSpan()/2,seen=new Set();return dxSpots.filter(s=>{if(!Number.isFinite(s.freq)||Math.abs(s.freq-freq)>half)return false;const key=Math.round(s.freq/100);if(seen.has(key))return false;seen.add(key);return true}).slice(0,12)}
function drawWaterOverlay(){
 const w=waterOverlay.width,h=waterOverlay.height,scale=w/1000,viewSpan=waterfallSpan(),centre=w/2,[lo,hi]=filterEdges();ox.clearRect(0,0,w,h);dxHits=[];
 const x1=Math.max(0,centre+lo/viewSpan*w),x2=Math.min(w,centre+hi/viewSpan*w);ox.fillStyle='rgba(255,232,75,.06)';ox.fillRect(x1,0,Math.max(0,x2-x1),h);ox.strokeStyle='#ffe85b';ox.lineWidth=scale;ox.beginPath();ox.moveTo(centre,0);ox.lineTo(centre,h);ox.stroke();
 ox.font=(9*scale)+'px Arial';ox.fillStyle='#ffe85b';ox.fillText('RX',centre+4*scale,h-8*scale);
 if(dxOverlay){let i=0;const spots=visibleDX();for(const spot of spots){const x=centre+(spot.freq-freq)/viewSpan*w,boxW=Math.min(w,(spot.call.length*6+12)*scale),boxH=15*scale,y=(i++%3)*17*scale+3*scale,left=Math.max(0,Math.min(w-boxW,x-boxW/2));ox.strokeStyle='#ff91ed';ox.lineWidth=scale;ox.beginPath();ox.moveTo(x,y+boxH);ox.lineTo(x,h);ox.stroke();ox.fillStyle='rgba(6,8,22,.92)';ox.fillRect(left,y,boxW,boxH);ox.strokeRect(left,y,boxW,boxH);ox.fillStyle='#ffb8f4';ox.fillText(spot.call,left+5*scale,y+11*scale);dxHits.push({left,top:y,width:boxW,height:boxH,spot})}
  if(!dxBusy)$('dx-overlay-status').textContent=dxError?'DX unavailable'+(dxSpots.length?' · cached spots':''):dxSpots.length?spots.length+' DX spots in view':'No DX spots loaded';
 }
}
for(const c of[spec,water,waterOverlay])c.onclick=e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*c.width,y=(e.clientY-r.top)/r.height*c.height,left=c===spec?32*c.width/1000:0;if(c===waterOverlay){const hit=dxHits.find(h=>x>=h.left&&x<=h.left+h.width&&y>=h.top&&y<=h.top+h.height);if(hit){stopScan();tune(hit.spot.freq);message('Tuned DX '+hit.spot.call+' · '+mode+' retained');return}}if(x<left)return;stopScan();tune(freq+((x-left)/(c.width-left)-.5)*(c===spec?span:waterfallSpan()))};
waterOverlay.onmousemove=e=>{const r=waterOverlay.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*waterOverlay.width,y=(e.clientY-r.top)/r.height*waterOverlay.height,hit=dxHits.find(h=>x>=h.left&&x<=h.left+h.width&&y>=h.top&&y<=h.top+h.height);waterOverlay.style.cursor=hit?'pointer':'crosshair';waterOverlay.title=hit?hit.spot.call+' · '+(hit.spot.freq/1e6).toFixed(6)+' MHz · '+hit.spot.time+' UTC':'RX marker · click waterfall to tune'};
$('water-span').onchange=()=>{waterSpanChoice=+$('water-span').value;clearWater();if(!frozen)draw();try{localStorage.setItem('hamtec-water-span',String(waterSpanChoice))}catch{}};
try{const saved=Number(localStorage.getItem('hamtec-water-span'));if([0,10000,25000,50000,100000,250000,500000,1024000].includes(saved)){waterSpanChoice=saved;$('water-span').value=saved}}catch{}
setInterval(()=>{$('clock').textContent='UTC '+new Date().toISOString().slice(11,19);if($('settings').open)details();if(live&&lastFrame&&performance.now()-lastFrame>5000)$('live').textContent='USB STALE'},1000);
updateFront();spectrumSettings();$('wf-gain').oninput();setMode(mode);tune(freq);renderMemory();clearWater();draw();connect();


function renderDX(){const tbody=$('dx-spots');tbody.replaceChildren();for(const spot of dxSpots.filter(s=>!$('dx-band').value||s.band===$('dx-band').value)){const tr=document.createElement('tr');for(const text of[spot.time,(spot.freq/1e6).toFixed(6),spot.call,spot.spotter,spot.comment]){const td=document.createElement('td');td.textContent=text;tr.append(td)}const b=document.createElement('button');b.textContent=(spot.freq/1e6).toFixed(6);b.title='Tune '+spot.call+'; retain '+mode+' mode';b.onclick=()=>{stopScan();tune(spot.freq);message('Tuned '+spot.call+' · '+mode+' mode retained');$('dx-dialog').close()};tr.children[1].replaceChildren(b);tbody.append(tr)}if(!tbody.children.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.textContent='No spots for this band.';tr.append(td);tbody.append(tr)}}
async function refreshDX(){if(dxBusy)return;dxBusy=true;if(dxOverlay)$('dx-overlay-status').textContent='Fetching DX…';$('dx-refresh').disabled=true;$('dx-status').textContent='Fetching HamQTH spots…';try{const r=await fetch('/api/dx-spots',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'DX feed unavailable');dxSpots=j.spots;dxError='';renderDX();$('dx-status').textContent='Fetched '+j.fetched_at+' · newest report '+(dxSpots[0]?.time||'none')+' UTC · '+dxSpots.length+' spots within RTL range. Check report dates.'}catch(e){dxError=e.message;$('dx-status').textContent='DX feed unavailable: '+e.message+(dxSpots.length?' · previous spots retained.':'')}finally{dxBusy=false;$('dx-refresh').disabled=false;drawWaterOverlay()}}
$('dx-cluster').onclick=()=>{if(!$('dx-dialog').open)$('dx-dialog').showModal();refreshDX();startDXPolling()};$('dx-close').onclick=()=>$('dx-dialog').close();$('dx-dialog').addEventListener('close',stopDXPollingIfUnused);$('dx-refresh').onclick=refreshDX;$('dx-band').onchange=renderDX;

$('nb').onclick=()=>{nb=!nb;updateNoise();send();message('Noise blanker '+(nb?'ON':'OFF'))};$('nr').onclick=()=>{nr=!nr;updateNoise();send();message('Noise reduction '+(nr?'ON':'OFF'))};
function noiseStrength(){nbStrength=+$('nb-strength').value;nrStrength=+$('nr-strength').value;$('nb-strength-value').textContent=nbStrength+'%';$('nr-strength-value').textContent=nrStrength+'%';send();try{localStorage.setItem('hamtec-noise-strength',JSON.stringify({nb:nbStrength,nr:nrStrength}))}catch{}}
for(const id of ['nb-strength','nr-strength'])$(id).oninput=noiseStrength;
try{const saved=JSON.parse(localStorage.getItem('hamtec-noise-strength')||'null');if(saved){if(Number.isInteger(saved.nb)&&saved.nb>=0&&saved.nb<=100)$('nb-strength').value=saved.nb;if(Number.isInteger(saved.nr)&&saved.nr>=0&&saved.nr<=100)$('nr-strength').value=saved.nr}}catch{}noiseStrength();
const defaultTheme={background:'#050a0e',panel:'#173a53',accent:'#00b9f0'};let theme={...defaultTheme};
function shade(hex,factor){return '#'+hex.slice(1).match(/../g).map(v=>Math.round(parseInt(v,16)*factor).toString(16).padStart(2,'0')).join('')}
function applyTheme(){const style=document.documentElement.style;style.setProperty('--theme-background',theme.background);const rgb=theme.background.slice(1).match(/../g).map(v=>parseInt(v,16));style.setProperty('--theme-foreground',rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>150?'#10202d':'#dce8f7');style.setProperty('--theme-panel',theme.panel);style.setProperty('--theme-panel-dark',shade(theme.panel,.3));style.setProperty('--theme-accent',theme.accent);style.setProperty('--theme-glow',theme.accent+'66');for(const key of Object.keys(defaultTheme))$('theme-'+key).value=theme[key];try{localStorage.setItem('hamtec-colours',JSON.stringify(theme))}catch{}}
for(const key of Object.keys(defaultTheme))$('theme-'+key).oninput=e=>{if(/^#[0-9a-f]{6}$/i.test(e.target.value)){theme[key]=e.target.value;applyTheme()}};
for(const [name,hex] of [['Red','#ff4f54'],['Orange','#ff9b32'],['Yellow','#ffe24c'],['Green','#44ef83'],['Cyan','#00b9f0'],['Blue','#567aff'],['Violet','#b469ff'],['Pink','#ff66cb']]){const b=document.createElement('button');b.type='button';b.title=name;b.setAttribute('aria-label',name+' colour theme');b.style.background=hex;b.onclick=()=>{theme={background:shade(hex,.08),panel:shade(hex,.28),accent:hex};applyTheme()};$('rainbow').append(b)}
$('theme-reset').onclick=()=>{theme={...defaultTheme};applyTheme()};try{const saved=JSON.parse(localStorage.getItem('hamtec-colours')||'null');if(saved)for(const key of Object.keys(defaultTheme))if(typeof saved[key]==='string'&&/^#[0-9a-f]{6}$/i.test(saved[key]))theme[key]=saved[key]}catch{}applyTheme();

function fitFrequency(){const input=$('freq'),w=input.clientWidth;if(!w)return;input.style.fontSize=Math.min(input.clientHeight?input.clientHeight-2:58,58,Math.max(16,(w-10)/(.61*input.value.length)))+'px'}
if(typeof ResizeObserver==='function')new ResizeObserver(fitFrequency).observe($('freq'));
if(typeof window!=='undefined')window.addEventListener('resize',fitFrequency);fitFrequency();
const channelGroups={
 'MARINE UK':{step:25000,filter:25000,start:156800000,note:'Common marine voice channels used in the UK. FM mode. Channel 80 has separate ship and shore frequencies; choose the side to receive.',channels:[[16,156800000],[6,156300000],[8,156400000],[9,156450000],[10,156500000],[11,156550000],[12,156600000],[13,156650000],[14,156700000],[15,156750000],[17,156850000],[67,156375000],[68,156425000],[69,156475000],[71,156575000],[72,156625000],[73,156675000],[74,156725000],[77,156875000],['80 SHIP',157025000],['80 SHORE',161625000]].map(([channel,freq])=>({channel,freq}))},
 'PMR UK':{step:12500,filter:12500,start:446006250,note:'Analogue PMR446 channels 1–16 · FM · 12.5 kHz spacing. Digital PMR voice and CTCSS/DCS decoding are not included.',channels:Array.from({length:16},(_,i)=>({channel:i+1,freq:446006250+i*12500}))}
};
function tuneChannel(group,hz){stopScan();setMode('NFM');bandwidth=group.filter;$('filter').value=bandwidth;$('filter-text').textContent=bandwidth/1000+'k';$('step').value=group.step;$('step').onchange();tune(hz)}
function openChannels(name){const group=channelGroups[name];tuneChannel(group,group.start);$('channels-title').textContent=name+' · CHANNEL PRESETS';$('channels-note').textContent=group.note;const list=$('channel-list');list.replaceChildren();for(const c of group.channels){const b=document.createElement('button');b.textContent='CH '+c.channel+' · '+(c.freq/1e6).toFixed(6)+' MHz';b.onclick=()=>{tuneChannel(group,c.freq);$('channels-dialog').close();message(name+' CH '+c.channel)};list.append(b)}$('channels-dialog').showModal()}
$('channels-close').onclick=()=>$('channels-dialog').close();

$('freq-step').onclick=$('step-label').onclick;$('step').onchange();

function startDXPolling(){if(!dxTimer)dxTimer=setInterval(refreshDX,30000)}
function stopDXPollingIfUnused(){if(!dxOverlay&&!$('dx-dialog').open){clearInterval(dxTimer);dxTimer=null}}
$('dx-overlay-toggle').onclick=()=>{dxOverlay=!dxOverlay;$('dx-overlay-toggle').textContent=dxOverlay?'DX ON':'DX OFF';$('dx-overlay-toggle').classList.toggle('green',dxOverlay);$('dx-overlay-toggle').setAttribute('aria-pressed',String(dxOverlay));if(dxOverlay){refreshDX();startDXPolling()}else{$('dx-overlay-status').textContent='';stopDXPollingIfUnused()}drawWaterOverlay()};
